"""create work orders table

Revision ID: 07a94ceea869
Revises: 8236cec0b5e1
Create Date: 2026-08-26 00:08:17.888653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07a94ceea869'
down_revision: Union[str, Sequence[str], None] = '8236cec0b5e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_request_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['maintenance_request_id'], ['maintenance_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_assigned_to'), 'work_orders', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_maintenance_request_id'), 'work_orders', ['maintenance_request_id'], unique=False)
    op.create_index(op.f('ix_work_orders_priority'), 'work_orders', ['priority'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_priority'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_maintenance_request_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_assigned_to'), table_name='work_orders')
    op.drop_table('work_orders')
    # ### end Alembic commands ###
