"""create facility booking tables

Revision ID: 3434d4c22685
Revises: 370cc520cd15
Create Date: 2026-08-27 00:02:03.683747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3434d4c22685'
down_revision: Union[str, Sequence[str], None] = '370cc520cd15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=True)
    op.create_index(op.f('ix_facilities_status'), 'facilities', ['status'], unique=False)
    op.create_table('facility_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('booking_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_bookings_booking_date'), 'facility_bookings', ['booking_date'], unique=False)
    op.create_index(op.f('ix_facility_bookings_facility_id'), 'facility_bookings', ['facility_id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_id'), 'facility_bookings', ['id'], unique=False)
    op.create_index(op.f('ix_facility_bookings_status'), 'facility_bookings', ['status'], unique=False)
    op.create_index(op.f('ix_facility_bookings_tenant_id'), 'facility_bookings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facility_bookings_tenant_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_status'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_facility_id'), table_name='facility_bookings')
    op.drop_index(op.f('ix_facility_bookings_booking_date'), table_name='facility_bookings')
    op.drop_table('facility_bookings')
    op.drop_index(op.f('ix_facilities_status'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
