"""create parking table

Revision ID: 370cc520cd15
Revises: be71d0f5685a
Create Date: 2026-08-26 14:29:18.981129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370cc520cd15'
down_revision: Union[str, Sequence[str], None] = 'be71d0f5685a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('parking_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=True),
    sa.Column('vehicle_type', sa.String(length=30), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_id'), 'parking', ['id'], unique=False)
    op.create_index(op.f('ix_parking_parking_number'), 'parking', ['parking_number'], unique=False)
    op.create_index(op.f('ix_parking_property_id'), 'parking', ['property_id'], unique=False)
    op.create_index(op.f('ix_parking_status'), 'parking', ['status'], unique=False)
    op.create_index(op.f('ix_parking_tenant_id'), 'parking', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_parking_vehicle_number'), 'parking', ['vehicle_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_vehicle_number'), table_name='parking')
    op.drop_index(op.f('ix_parking_tenant_id'), table_name='parking')
    op.drop_index(op.f('ix_parking_status'), table_name='parking')
    op.drop_index(op.f('ix_parking_property_id'), table_name='parking')
    op.drop_index(op.f('ix_parking_parking_number'), table_name='parking')
    op.drop_index(op.f('ix_parking_id'), table_name='parking')
    op.drop_table('parking')
    # ### end Alembic commands ###
